config/routes.rb
Rails.application.routes.draw do
  get 'home/front'

  get 'todos/index'
  get 'todos/new'
  get 'todos/edit'

  devise_for :users

  resources :users do 
    resources :todos
  end
  root to: "home#front"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :authenticate_user!
  before_action :check_user
  def index
      @user = User.find(params[:user_id])
      @todos = @user.todos
  end

  def new
    @user = User.find(params[:user_id])
    @todo = @user.todos.new
  end

  def create
    @user = User.find(params[:user_id])
    @todo = @user.todos.create(todo_params)
    if @todo.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])
    @todo.destroy
    redirect_to action: 'index'
  end

  def show
    @user = User.find(params[:user_id])
    @todo = @user.todos.find(params[:id])
  end

  def edit
  end


  private
  def check_user
    if current_user != User.find(params[:user_id])
      redirect_to root_path
    end 
  end

  def todo_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/front.html.erb
<h1> Generate todos. Get it done!</h1>
</br>
<%= link_to " Create New Todo", new_user_todo_path(current_user, @todo) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genesis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Genesis</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "My Todos", user_todos_path(current_user), class: 'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
        </li>

      <% end %>
    
      
    </ul>
  </div>
</nav>

app/views/todos/_form.html.erb
<%= form_with model: ([@user, @todo]) do |f| %>
    Task Title: 
    <%= f.text_field :title %>
    Task Description: 
    <%= f.text_field :description %>

    <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<h1>My Todos</h1>

<% @todos.each do |todo| %>
    <li>
        <%= todo.title %>:
        <%= todo.description %>
        <%= link_to 'Delete', user_todo_path(current_user, todo), method: :delete %>
    </li>
<% end %>

</br>
<%= link_to "New Todo", new_user_todo_path(current_user, @todo) %>

app/views/todos/new.html.erb
<h1>Create a new task!</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<%= @todo.title %>:
<%= @todo.description %>